site_name: ぼかろすきー Docs
copyright: Copyright &copy; 2024-2025 Reliwave / Reliwave P.S.
theme:
  name: material
  language: ja
  logo: assets/vocaloid.png
  favicon: assets/vocaloid.png
nav:
  - ホーム: index.md
  - New! 利用規約: tos.md
  - New! 簡易利用規約: tos-simple.md
  - Regacy 利用規約: regtos.md
  - NSFWガイドライン: nsfw.md
  - プライバシーポリシー: privacy.md

markdown_extensions:
  - attr_list
  - md_in_html