name: ci 
on:
  push:
    branches:
      - master 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: git pull --rebase origin gh-pages
      - run: mkdocs build
      - run: |
          git fetch origin gh-pages
          git worktree add gh-pages
          cd gh-pages
          git reset --hard origin/gh-pages
          cd ..
          cp -r site/* gh-pages/
          cd gh-pages
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            MKDOCS_VERSION=$(mkdocs --version | awk '{print $1, $2}')
            COMMIT_HASH=$(git rev-parse --short origin/master)
            git commit -m "Deploy: ${COMMIT_HASH} with MkDocs version: ${MKDOCS_VERSION}"
            git push origin gh-pages --force
          else
            echo "No changes to commit"
          fi